# Generated by Django 5.0.6 on 2024-06-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_inning_game'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
    ]
