# Generated by Django 5.0.6 on 2024-06-24 23:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inning',
            name='bottom_frame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inning_of_bottom', to='games.frame'),
        ),
        migrations.AlterField(
            model_name='inning',
            name='top_frame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inning_of_top', to='games.frame'),
        ),
    ]
